spring:
  application:
    name: TaskManager

  datasource:
    url: jdbc:postgresql://localhost:5432/TaskManager
    username: postgres
    password: 0258
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/master.xml
    enabled: true

  jpa:
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
#      hibernate.boot.allow_jdbc_metadata_access: false
#      hibernate.temp.use_jdbc_metadata_defaults: false

      # modify batch size as necessary
      hibernate.jdbc.batch_size: 25
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true
      hibernate.cache.use_minimal_puts: true

      hibernate.connection.url: jdbc:postgresql://localhost:5432/TaskManager
      hibernate.connection.driver_class: org.postgresql.Driver
      hibernate.connection.username: postgres
      hibernate.connection.password: 0258
#      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  api-docs:
    path: /api-docs


#  jpa:
#    hibernate:
#      ddl-auto: none
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true


#  logging:
#    level:
#      hibernate": debug
#      root: info
#      web: info
