spring:
  application:
    name: TaskManager

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/master.xml
    enabled: true

  jpa:
    open-in-view: true
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
#      hibernate.boot.allow_jdbc_metadata_access: false
#      hibernate.temp.use_jdbc_metadata_defaults: false

      # modify batch size as necessary
      hibernate.jdbc.batch_size: 25
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true
      hibernate.cache.use_minimal_puts: true


#      hibernate.connection.url:
#      hibernate.connection.driver_class: org.postgresql.Driver
#      hibernate.connection.username:
#      hibernate.connection.password:
#      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  api-docs:
    path: /api-docs

security:
  jwt:
    secret-key: ${SECRET_KEY}
    expiration-time: ${EXPIRATION_TIME}

logging:
  level:
    root: "DEBUG"
    org.springframework: "TRACE"
    org.hibernate: "TRACE"


#  jpa:
#    hibernate:
#      ddl-auto: none
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true



